//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.10 at 04:31:51 PM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.gailo22.com/Employee", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package myproject.serialize;
